server:
  port: 8761  # Eureka server will run on port 8761

eureka:
  client:
    registerWithEureka: false   # Don't register this server itself with Eureka
    fetchRegistry: false         # Don't fetch registry (Eureka Client behavior)
  server:
    enableSelfPreservation: false